// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1m9hX7axiOTPb5mA_VQRoDs4MZTRNRo',
    appId: '1:818155574580:web:fd8cbf0af5f035c6f64161',
    messagingSenderId: '818155574580',
    projectId: 'gardening-by-the-moon',
    authDomain: 'gardening-by-the-moon.firebaseapp.com',
    databaseURL: 'https://gardening-by-the-moon.firebaseio.com',
    storageBucket: 'gardening-by-the-moon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBctgUSDODSi7em3IxpOwzhoK0eLSU3Ng4',
    appId: '1:818155574580:ios:8459635ac2e5f421',
    messagingSenderId: '818155574580',
    projectId: 'gardening-by-the-moon',
    databaseURL: 'https://gardening-by-the-moon.firebaseio.com',
    storageBucket: 'gardening-by-the-moon.appspot.com',
    androidClientId:
        '818155574580-9u4cvt2auq3kir6r8600pn9spdf3vvc5.apps.googleusercontent.com',
    iosClientId:
        '818155574580-q6up9ob3oqab5vc81fd160vislc9uco0.apps.googleusercontent.com',
    iosBundleId: 'fr.ilandes.lunargarden',
  );
}
